# Sample compose.yml for VPS deployment at /opt/preprod/compose.yml
# This file should be placed on your VPS at /opt/preprod/compose.yml

version: '3.8'

services:
  website:
    image: ghcr.io/dmitrybond-tech/website:main
    pull_policy: always
    container_name: preprod-website
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - preprod-network

networks:
  preprod-network:
    driver: bridge
