backend:
  name: github
  repo: dmitrybond-tech/personal-website-dev
  branch: main
  base_url: "http://localhost:4321"
  auth_endpoint: "oauth"

publish_mode: simple

media_folder: "apps/website/src/content/en/assets"
public_folder: "/media/en"

i18n:
  structure: multiple_folders
  locales: [en, ru]
  default_locale: en

collections:
  - name: "posts"
    label: "Blog posts"
    folder: "apps/website/src/content/posts"
    create: true
    format: "frontmatter"
    extension: "md"
    slug: "{{slug}}"
    path: "{{locale}}/{{slug}}"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: "translate" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false, default: "{{now}}", i18n: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, i18n: false }
      - { label: "Description", name: "description", widget: "text", required: false, i18n: "translate" }
      - { label: "Body", name: "body", widget: "markdown", i18n: "translate" }

  - name: "en_about"
    label: "About Page (EN)"
    folder: "apps/website/src/content/aboutPage/en"
    create: false
    format: "frontmatter"
    extension: "mdx"
    slug: "about"
    media_folder: "apps/website/public/uploads"
    public_folder: "/uploads"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      
      # Profile Section
      - label: "Profile"
        name: "profile"
        widget: "object"
        required: false
        fields:
          - { label: "Full Name", name: "fullName", widget: "string", required: false }
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Avatar", name: "avatar", widget: "image", required: false }
      
      # Sections (Section Builder)
      - label: "Sections"
        name: "sections"
        widget: "list"
        required: false
        fields:
          - { label: "ID", name: "id", widget: "string", required: false }
          - { label: "Type", name: "type", widget: "select", options: ["hero", "skills", "experience", "education", "projects", "testimonials", "favorites"] }
          - { label: "Heading", name: "heading", widget: "string", required: false }
          - { label: "Icon", name: "icon", widget: "string", required: false }
          - { label: "Image", name: "image", widget: "image", required: false }
          - label: "Data"
            name: "data"
            widget: "object"
            required: false
            fields:
              - label: "Groups"
                name: "groups"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - label: "Items"
                    name: "items"
                    widget: "list"
                    fields:
                      - { label: "Name", name: "name", widget: "string" }
                      - { label: "Icon", name: "icon", widget: "string", required: false }
                      - { label: "URL", name: "url", widget: "string", required: false }
                      - { label: "Level (1-5)", name: "level", widget: "number", min: 1, max: 5, required: false }
                      - label: "Description"
                        name: "description"
                        widget: "object"
                        required: false
                        fields:
                          - { label: "English", name: "en", widget: "text", required: false }
                          - { label: "Russian", name: "ru", widget: "text", required: false }
      
      # Global links and files
      - label: "Links"
        name: "links"
        widget: "list"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Icon", name: "icon", widget: "string", required: false }
      - { label: "CV PDF", name: "cv_pdf", widget: "string", required: false }
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        field: { label: "Image", name: "image", widget: "string" }

  - name: "ru_about"
    label: "About Page (RU)"
    folder: "apps/website/src/content/aboutPage/ru"
    create: false
    format: "frontmatter"
    extension: "mdx"
    slug: "about"
    media_folder: "apps/website/public/uploads"
    public_folder: "/uploads"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      
      # Profile Section
      - label: "Profile"
        name: "profile"
        widget: "object"
        required: false
        fields:
          - { label: "Full Name", name: "fullName", widget: "string", required: false }
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Avatar", name: "avatar", widget: "image", required: false }
      
      # Sections (Section Builder)
      - label: "Sections"
        name: "sections"
        widget: "list"
        required: false
        fields:
          - { label: "ID", name: "id", widget: "string", required: false }
          - { label: "Type", name: "type", widget: "select", options: ["hero", "skills", "experience", "education", "projects", "testimonials", "favorites"] }
          - { label: "Heading", name: "heading", widget: "string", required: false }
          - { label: "Icon", name: "icon", widget: "string", required: false }
          - { label: "Image", name: "image", widget: "image", required: false }
          - label: "Data"
            name: "data"
            widget: "object"
            required: false
            fields:
              - label: "Groups"
                name: "groups"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - label: "Items"
                    name: "items"
                    widget: "list"
                    fields:
                      - { label: "Name", name: "name", widget: "string" }
                      - { label: "Icon", name: "icon", widget: "string", required: false }
                      - { label: "URL", name: "url", widget: "string", required: false }
                      - { label: "Level (1-5)", name: "level", widget: "number", min: 1, max: 5, required: false }
                      - label: "Description"
                        name: "description"
                        widget: "object"
                        required: false
                        fields:
                          - { label: "English", name: "en", widget: "text", required: false }
                          - { label: "Russian", name: "ru", widget: "text", required: false }
      
      # Global links and files
      - label: "Links"
        name: "links"
        widget: "list"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Icon", name: "icon", widget: "string", required: false }
      - { label: "CV PDF", name: "cv_pdf", widget: "string", required: false }
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        field: { label: "Image", name: "image", widget: "string" }

  - name: "en_bookme"
    label: "Book.me Config (EN)"
    folder: "apps/website/src/content/bookmeConfig/en"
    create: false
    format: "yaml"
    extension: "yaml"
    slug: "config"
    fields:
      - { label: "Page Title", name: "page_title", widget: "string", required: false }
      - { label: "Page Subtitle", name: "page_subtitle", widget: "text", required: false }
      - label: "Cal.com Configuration"
        name: "cal"
        widget: "object"
        fields:
          - { label: "Handle", name: "handle", widget: "string" }
          - { label: "Event Type", name: "eventType", widget: "string", required: false }
          - label: "Attributes"
            name: "attrs"
            widget: "object"
            required: false
            fields:
              - { label: "Hide Event Type Details", name: "hideEventTypeDetails", widget: "string", required: false }
      - label: "Booking Tiles"
        name: "tiles"
        widget: "list"
        fields:
          - { label: "ID", name: "id", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text", required: false }
          - { label: "Image", name: "image", widget: "string", required: false }
          - { label: "CTA Text", name: "cta_text", widget: "string" }
          - { label: "CTA Kind", name: "cta_kind", widget: "select", options: ["cal", "link", "mailto", "download"] }
          - { label: "Cal Preset", name: "cal_preset", widget: "string", required: false }
          - { label: "Href", name: "href", widget: "string", required: false }
          - { label: "Visible", name: "visible", widget: "boolean" }
          - { label: "Icon", name: "icon", widget: "string", required: false }
      - { label: "Footer Note", name: "footer_note", widget: "text", required: false }

  - name: "ru_bookme"
    label: "Book.me Config (RU)"
    folder: "apps/website/src/content/bookmeConfig/ru"
    create: false
    format: "yaml"
    extension: "yaml"
    slug: "config"
    fields:
      - { label: "Page Title", name: "page_title", widget: "string", required: false }
      - { label: "Page Subtitle", name: "page_subtitle", widget: "text", required: false }
      - label: "Cal.com Configuration"
        name: "cal"
        widget: "object"
        fields:
          - { label: "Handle", name: "handle", widget: "string" }
          - { label: "Event Type", name: "eventType", widget: "string", required: false }
          - label: "Attributes"
            name: "attrs"
            widget: "object"
            required: false
            fields:
              - { label: "Hide Event Type Details", name: "hideEventTypeDetails", widget: "string", required: false }
      - label: "Booking Tiles"
        name: "tiles"
        widget: "list"
        fields:
          - { label: "ID", name: "id", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text", required: false }
          - { label: "Image", name: "image", widget: "string", required: false }
          - { label: "CTA Text", name: "cta_text", widget: "string" }
          - { label: "CTA Kind", name: "cta_kind", widget: "select", options: ["cal", "link", "mailto", "download"] }
          - { label: "Cal Preset", name: "cal_preset", widget: "string", required: false }
          - { label: "Href", name: "href", widget: "string", required: false }
          - { label: "Visible", name: "visible", widget: "boolean" }
          - { label: "Icon", name: "icon", widget: "string", required: false }
      - { label: "Footer Note", name: "footer_note", widget: "text", required: false }

  - name: "en_bookme_content"
    label: "Book Me Page (EN)"
    folder: "apps/website/src/content"
    create: false
    format: "frontmatter"
    extension: "md"
    slug: "bookme"
    path: "en/bookme"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "CTA", name: "cta", widget: "string" }
      - { label: "Default Tile Slug", name: "defaultTileSlug", widget: "string" }
      - label: "Tiles"
        name: "tiles"
        widget: "list"
        fields:
          - { label: "Slug", name: "slug", widget: "string" }
          - { label: "Label", name: "label", widget: "string", required: false }
          - { label: "Caption", name: "caption", widget: "string", required: false }
          - { label: "Icon", name: "icon", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "ru_bookme_content"
    label: "Book Me Page (RU)"
    folder: "apps/website/src/content"
    create: false
    format: "frontmatter"
    extension: "md"
    slug: "bookme"
    path: "ru/bookme"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "CTA", name: "cta", widget: "string" }
      - { label: "Default Tile Slug", name: "defaultTileSlug", widget: "string" }
      - label: "Tiles"
        name: "tiles"
        widget: "list"
        fields:
          - { label: "Slug", name: "slug", widget: "string" }
          - { label: "Label", name: "label", widget: "string", required: false }
          - { label: "Caption", name: "caption", widget: "string", required: false }
          - { label: "Icon", name: "icon", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }