backend:
  name: github
  repo: dmitrybond-tech/personal-website-dev
  branch: main
  site_domain: "dmitrybond.tech"
  base_url: "https://dmitrybond.tech"
  auth_endpoint: "oauth"
media_folder: "public/uploads"
public_folder: "/uploads"
site_url: "/"
display_url: "/"
slug:
  encoding: "unicode"
  clean_accents: true
i18n:
  structure: multiple_folders
  locales: [en, ru]
  default_locale: en
collections:
  - name: "blog"
    label: "Blog"
    folder: "apps/website/src/content/blog"
    create: true
    extension: "md"
    i18n: false
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "lang", label: "Lang", widget: "select", options: ["en","ru"], default: "en" }
      - { name: "publishedAt", label: "Published At", widget: "datetime" }
      - { name: "description", label: "Description", widget: "text", required: false }
      - { name: "tags", label: "Tags", widget: "list", default: [] }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "about"
    label: "About Page"
    folder: "apps/website/src/content/pages/about"
    format: "json"
    extension: "json"
    create: false
    i18n: true
    slug: "index"
    fields:
      - { name: "route", label: "Route", widget: "string", i18n: true }
      - { name: "title", label: "Title", widget: "string", i18n: true }
      - label: "Blocks"
        name: "blocks"
        widget: "list"
        i18n: true
        types:
          - label: "Heading"
            name: "heading"
            widget: "object"
            i18n: true
            fields:
              - { name: "text", label: "Text", widget: "string", i18n: true }
          - label: "Text"
            name: "text"
            widget: "object"
            i18n: true
            fields:
              - { name: "md", label: "Markdown", widget: "markdown", i18n: true }
          - label: "Items"
            name: "items"
            widget: "object"
            i18n: true
            fields:
              - name: "items"
                label: "Items"
                widget: "list"
                i18n: true
                fields:
                  - { name: "label", widget: "string", i18n: true }
                  - { name: "value", widget: "string", i18n: true }
  - name: "bookme"
    label: "BookMe Page"
    folder: "apps/website/src/content/pages/bookme"
    format: "json"
    extension: "json"
    create: false
    i18n: true
    slug: "index"
    fields:
      - { name: "route", label: "Route", widget: "string", i18n: true }
      - { name: "title", label: "Title", widget: "string", i18n: true }
      - { name: "intro", label: "Intro", widget: "markdown", required: false, i18n: true }
      - name: "events"
        label: "Events"
        widget: "list"
        i18n: true
        fields:
          - { name: "id", label: "Event ID", widget: "string", i18n: true }
          - { name: "label", label: "Label", widget: "string", i18n: true }
          - { name: "link", label: "Cal Link", widget: "string", i18n: true }
  - name: "footer"
    label: "Footer"
    folder: "apps/website/src/content/footer"
    format: "json"
    extension: "json"
    create: false
    i18n: true
    slug: "index"
    fields:
      - { name: "brandLine", label: "Brand Line", widget: "string", i18n: true }
      - name: "links"
        label: "Links"
        widget: "list"
        i18n: true
        fields:
          - { name: "label", label: "Label", widget: "string" }
          - { name: "href", label: "URL", widget: "string" }
          - { name: "external", label: "External Link", widget: "boolean", default: false, required: false }
      - name: "legal"
        label: "Legal Links"
        widget: "object"
        i18n: true
        fields:
          - { name: "privacyUrl", label: "Privacy Policy URL", widget: "string" }
          - { name: "termsUrl", label: "Terms of Service URL", widget: "string" }
          - { name: "cookiesUrl", label: "Cookie Policy URL", widget: "string" }
      - name: "consent"
        label: "Cookie Consent"
        widget: "object"
        i18n: true
        required: false
        fields:
          - { name: "bannerText", label: "Banner Text", widget: "markdown", required: false }
          - { name: "acceptLabel", label: "Accept Button Label", widget: "string", required: false }
          - { name: "manageLabel", label: "Manage Button Label", widget: "string", required: false }