backend:
  name: github
  repo: dmitrybond-tech/personal-website-dev
  branch: main
  base_url: "http://localhost:4321"
  auth_endpoint: "oauth"

publish_mode: simple

media_folder: "apps/website/public/uploads"
public_folder: "/uploads"

i18n:
  structure: multiple_folders
  locales: [en, ru]
  default_locale: en

collections:
  - name: "posts"
    label: "Blog posts"
    folder: "apps/website/src/content/posts"
    create: true
    format: "frontmatter"
    extension: "md"
    slug: "{{slug}}"
    path: "{{locale}}/{{slug}}"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: "translate" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false, default: "{{now}}", i18n: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, i18n: false }
      - { label: "Description", name: "description", widget: "text", required: false, i18n: "translate" }
      - { label: "Body", name: "body", widget: "markdown", i18n: "translate" }