# Iconify Icons Configuration for Decap CMS
# This file contains the icon options for the skills section

iconify_icons:
  # General Skills
  - { label: "Discovery", value: "simple-icons:discovery" }
  - { label: "Delivery", value: "simple-icons:delivery" }
  - { label: "Analytics", value: "simple-icons:googleanalytics" }
  
  # Frameworks & Methodologies
  - { label: "ITIL", value: "simple-icons:itil" }
  - { label: "PMI", value: "simple-icons:projectmanagementinstitute" }
  - { label: "Agile", value: "simple-icons:agile" }
  - { label: "DevOps", value: "simple-icons:googlecloud" }
  - { label: "ISO", value: "simple-icons:iso" }
  - { label: "ESLint", value: "simple-icons:eslint" }
  
  # Technical Skills
  - { label: "AWS", value: "simple-icons:amazonaws" }
  - { label: "Linux", value: "simple-icons:linux" }
  - { label: "Web Components", value: "simple-icons:webcomponents" }
  - { label: "Python", value: "simple-icons:python" }
  - { label: "PostgreSQL", value: "simple-icons:postgresql" }
  - { label: "TensorFlow", value: "simple-icons:tensorflow" }
  
  # Languages (Flags)
  - { label: "UK Flag", value: "twemoji:flag-united-kingdom" }
  - { label: "Russia Flag", value: "twemoji:flag-russia" }
  - { label: "Netherlands Flag", value: "twemoji:flag-netherlands" }
  
  # Additional Popular Icons
  - { label: "React", value: "simple-icons:react" }
  - { label: "TypeScript", value: "simple-icons:typescript" }
  - { label: "Node.js", value: "simple-icons:nodedotjs" }
  - { label: "GitHub", value: "simple-icons:github" }
  - { label: "Docker", value: "simple-icons:docker" }
  - { label: "Kubernetes", value: "simple-icons:kubernetes" }
  - { label: "MongoDB", value: "simple-icons:mongodb" }
  - { label: "Redis", value: "simple-icons:redis" }
  - { label: "GraphQL", value: "simple-icons:graphql" }
  - { label: "Firebase", value: "simple-icons:firebase" }
  - { label: "Vercel", value: "simple-icons:vercel" }
  - { label: "Netlify", value: "simple-icons:netlify" }
  - { label: "Tailwind CSS", value: "simple-icons:tailwindcss" }
  - { label: "Sass", value: "simple-icons:sass" }
  - { label: "Webpack", value: "simple-icons:webpack" }
  - { label: "Jest", value: "simple-icons:jest" }
  - { label: "Cypress", value: "simple-icons:cypress" }
  - { label: "Figma", value: "simple-icons:figma" }
  - { label: "Sketch", value: "simple-icons:sketch" }
  - { label: "Adobe", value: "simple-icons:adobe" }
  - { label: "Photoshop", value: "simple-icons:adobephotoshop" }
  - { label: "Illustrator", value: "simple-icons:adobeillustrator" }
  - { label: "VS Code", value: "simple-icons:visualstudiocode" }
  - { label: "IntelliJ", value: "simple-icons:intellijidea" }
  - { label: "Slack", value: "simple-icons:slack" }
  - { label: "Discord", value: "simple-icons:discord" }
  - { label: "Telegram", value: "simple-icons:telegram" }
  - { label: "LinkedIn", value: "simple-icons:linkedin" }
  - { label: "Twitter", value: "simple-icons:twitter" }
  - { label: "Instagram", value: "simple-icons:instagram" }
  - { label: "YouTube", value: "simple-icons:youtube" }
  - { label: "Twitch", value: "simple-icons:twitch" }
  - { label: "Spotify", value: "simple-icons:spotify" }
  - { label: "Apple", value: "simple-icons:apple" }
  - { label: "Google", value: "simple-icons:google" }
  - { label: "Microsoft", value: "simple-icons:microsoft" }
  - { label: "Meta", value: "simple-icons:meta" }
  - { label: "Netflix", value: "simple-icons:netflix" }
  - { label: "Steam", value: "simple-icons:steam" }
  - { label: "PlayStation", value: "simple-icons:playstation" }
  - { label: "Xbox", value: "simple-icons:xbox" }
  - { label: "Nintendo", value: "simple-icons:nintendo" }
