name: Deploy Preprod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, preprod]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Compute image refs (lowercase)
        shell: bash
        run: |
          REPO_LC=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_MAIN=ghcr.io/${REPO_LC}:main" >> "$GITHUB_ENV"
          echo "IMAGE_SHA=ghcr.io/${REPO_LC}:sha-${{ github.sha }}" >> "$GITHUB_ENV"

      # Убеждаемся, что у пользователя раннера есть ~/.docker (персистентно между запусками)
      - name: Ensure runner docker config exists
        shell: bash
        run: |
          mkdir -p "$HOME/.docker"
          chmod 700 "$HOME/.docker"

      - name: Log in to GHCR (persist for self-hosted)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false  # не разлогиниваемся; креды сохранятся в $HOME/.docker/config.json

      # Простая верификация: проверим, что в конфиге есть запись ghcr.io и тестовый pull проходит
      - name: Verify Docker login
        shell: bash
        run: |
          if [ -f "$HOME/.docker/config.json" ]; then
            grep -q '"ghcr.io"' "$HOME/.docker/config.json" && echo "✓ ghcr.io auth present" || echo "⚠ ghcr.io auth not found"
          else
            echo "⚠ $HOME/.docker/config.json not found"
          fi
          docker pull hello-world:latest >/dev/null && echo "✓ docker pull works" || echo "⚠ docker pull failed"

      - name: Pull image (sha or main)
        shell: bash
        run: |
          set -euo pipefail
          echo "Attempting to pull: $IMAGE_SHA"
          if ! docker pull "$IMAGE_SHA"; then
            echo "Falling back to: $IMAGE_MAIN"
            docker pull "$IMAGE_MAIN"
          fi

      - name: Restart container
        shell: bash
        run: |
          set -euo pipefail
          docker rm -f website-preprod || true
          docker run -d --name website-preprod \
            -p 127.0.0.1:3000:3000 \
            -e NODE_ENV=production \
            "$IMAGE_SHA" || docker run -d --name website-preprod \
            -p 127.0.0.1:3000:3000 \
            -e NODE_ENV=production \
            "$IMAGE_MAIN"

      - name: Show running containers
        run: docker ps --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}'

      # Деплой на удаленную VPS через SSH
      - name: Setup SSH for VPS deployment
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/vps_key
          chmod 600 ~/.ssh/vps_key
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        shell: bash
        run: |
          set -euo pipefail
          echo "Deploying to VPS: ${{ secrets.VPS_HOST }}"
          
          # SSH команды для деплоя на VPS
          ssh -i ~/.ssh/vps_key -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -euo pipefail
            
            # Переходим в директорию с compose файлом
            cd /opt/preprod
            
            # Проверяем, что compose файл существует
            if [ ! -f compose.yml ]; then
              echo "ERROR: compose.yml not found in /opt/preprod"
              exit 1
            fi
            
            echo "=== Current compose.yml ==="
            head -20 compose.yml
            
            # Логинимся в GHCR на VPS
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            
            # Пуллим новый образ
            echo "Pulling latest image..."
            docker compose pull
            
            # Перезапускаем сервис
            echo "Restarting service..."
            docker compose up -d --no-deps --force-recreate
            
            # Очищаем старые образы
            docker image prune -f
            
            # Показываем статус
            echo "=== Running containers ==="
            docker ps --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}'
            
            # Проверяем здоровье сервиса
            echo "=== Health check ==="
            sleep 10
            if docker ps --filter "name=preprod-website" --filter "status=running" | grep -q preprod-website; then
              echo "✅ Service is running"
            else
              echo "❌ Service failed to start"
              docker logs preprod-website || echo "No logs available"
              exit 1
            fi
          EOF

      - name: Verify VPS deployment
        shell: bash
        run: |
          echo "Verifying deployment on VPS..."
          ssh -i ~/.ssh/vps_key -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            # Проверяем, что сервис отвечает
            if curl -f http://localhost:3000/ >/dev/null 2>&1; then
              echo "✅ Website is responding on VPS"
            else
              echo "❌ Website is not responding"
              exit 1
            fi
          EOF