name: Build & Deploy

on:
  push:
    branches: [ main ]

permissions: { contents: read, packages: write }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}  # хватает для push в GHCR
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:main
            ghcr.io/${{ github.repository }}:sha-${{ github.sha }}

  deploy:
    runs-on: self-hosted            # это твой VPS
    needs: build
    steps:
      - name: Pull & restart
        run: |
          docker login ghcr.io -u ${{ github.repository_owner }} -p '${{ secrets.GITHUB_TOKEN }}'
          cd /opt/preprod
          docker compose pull
          docker compose up -d
          docker image prune -f
